doomemacs/themes

doom-one-theme.el
This change works for me as a more visible selection color for ivy-mode. 
Although i am not very sure about blue being the right color to use here. 
What do you think?
=> Ivy mode - a more visible selection color

doom-molokai-theme.el, doom-one-theme.el
Hi, here are some face definitions that work with both term and ansi-term.
=> Add terminal colors

doom-themes-common.el
=> Add basic support for auctex faces

doom-themes-common.el
https://github.com/abo-abo/hydra
=> Add hydra faces

doom-themes-common.el
https://github.com/ledger/ledger-mode
Here's how it looks like with doom-one
=> Add ledger faces

doom-themes-common.el
I chose blue, but cyan might be more appropriate (I prefer the blue FWIW).
=> Theme link face

doom-themes-common.el
=> Theme eshell

themes/doom-one-theme.el
Besides brighter means brighter.
=> Do not confuse modeline and comment highlight.

themes/doom-peacock-theme.el
Wanted to try my hand at making a theme. This PR is very much a wip, but I thought I'd see if I could get some feedback if I'm in the right direction.
- I duplicated doom-one-theme as you suggested in #82 
- Opened up the peacock emacs theme [here](https://github.com/daylerees/colour-schemes/blob/master/emacs/peacock-theme.el) and looked through the colours in `rainbow-mode`
- I didn't expect this, but I was able to just load the theme and then continually eval the buffer and see the changes. I guess that's emacs goodness. Pretty cool.
- I arbitrarily chose some colours (`bg-alt`, for example). 
- I didn't know what to do for the the "16" coloumn of colours, so you'll see a couple `peacock todo 16` comments kicking around...
- I couldn't get operators to be red... 🤔 (see screenshot in the …
=> Peacock Theme

themes/doom-one-light-theme.el
Sorry for the mistake for the pull request. I just fix it...😂
=> Fix web-mode-current-element-highlight-face and helm-candidate-number

themes/doom-peacock-theme.el
=> fix the linum-relative-current-face for peacock-theme

themes/doom-peacock-theme.el
=> fix the issue #112 -> Problem with company popup on peacock theme

themes/doom-spacegrey-theme.el
Thought I'd take another crack at a theme. Here's my [spacegrey](http://kkga.github.io/spacegray/)
**Screenshots**
=> add spacegrey theme

themes/doom-one-light-theme.el
A quick fix for org-level faces and web-mode element highlight.
=> be consistent with other themes' org-level faces

themes/doom-dracula-theme.el
Fixed filename typo for dracula theme and changed its org-mode faces to match original
more closely (only in org-mode).
=> Fixed typo and made dracula theme more close to original.

themes/doom-dracula-theme.el
A very minor change but it makes overall effect much better.
=> Making tags color more consistent.

themes/doom-one-light-theme.el
Update ivy-posframe-cursor and resolve conflict between lsp highlight face and highlight face.
Thanks.
=> A few followup changes for lsp, ivy package updates for doom-one-light

README.md, doom-themes.el, themes/doom-opera-light-theme.el, themes/doom-opera-theme.el
=> Added doom-opera light and dark themes.

README.md, doom-themes.el, themes/doom-sourcerer-theme.el
=> Adding doom based sourcerer theme

README.md, doom-themes.el, themes/doom-Iosvkem-theme.el
=> Add doom-Iosvkem

themes/doom-tomorrow-night-theme.el
Very minor change but one that I think would look better
=> Change bg-alt for tomorrow-night to match atom

doom-themes-common.el
See https://github.com/akermu/emacs-libvterm
=> Add vterm support based on term

doom-themes-common.el
Adds support for https://github.com/clemera/objed
=> Add faces and vars for objed

themes/doom-molokai-theme.el
=> Fix #283 : Fixing and refactoring molokai

doom-themes-base.el, themes/doom-molokai-theme.el
Fixes #291. It looks very nice IMHO. I'll solve the solaire-mode problems in the solaire-mode's repo.
=> Add: Centaur tabs configuration

README.md, doom-themes.el, themes/doom-gruvbox-theme.el
Hi! I'm new to writing lisp/elisp, but I've had a go at porting over the gruvbox theme to doom.
Any feedback would be greatly appreciated :smiley: 
---
**Screenshots**
=> Gruvbox Theme

doom-themes-base.el
It add a face for directories in `all-the-icons-dired`.
=> Add: all-the-icons-dired dir face

doom-themes-base.el
Add some missing faces from `dired-k`.
=> Add: missing dired-k faces

doom-themes-base.el
Add smerges refined faces with same background value as magit.
=> Add: smerges refined faces

doom-themes-base.el
This face was not previously themed and is used by helm-occur, helm-ag...
=> Fontify helm-moccur-buffer as a link.

doom-themes-ext-treemacs.el
Update doom-colors according to doom-atom.
Make root icon bigger.
=> Make treemacs theme look better.

doom-themes-base.el
Just a single face needed for this mode, a red squiggle same as flycheck-error.
=> Add: face for pkgbuild-mode

README.md, doom-themes.el, themes/doom-laserwave-theme.el
New theme inspired by the vscode  [LaserWave Theme](https://github.com/Jaredk3nt/laserwave)
screenshot:
=> Add Laserwave theme

doom-themes-base.el
Use doom-lighten to make bright* variants actually brighterwq
=> Add 8-15 colors in vterm

doom-themes-base.el
These faces are used to define properly the segments for telephone-line
=> Add telephone-line-faces

themes/doom-moonlight-theme.el
I updated the colors for `doom-moonlight` to better match the current [vscode-moonlight-theme](https://github.com/atomiks/moonlight-vscode-theme)
=> Updated moonlight colors

themes/doom-ephemeral-theme.el
for your consideration, thanks (attempt 2 - electric boogaloo)
=> mod: added theme ephemeral

doom-themes-ext-treemacs.el
=> respects treemacs-fringe-indicator-mode

doom-themes-base.el
Add custom faces for the `minimal.el` based module proposed by https://github.com/hlissner/doom-emacs/pull/3142
=> Add faces for Minimap

themes/doom-manegarm-theme.el
This is related to issue #314 and commit 9cd6872
=> Disable byte-compilation of doom-manegarm-theme

themes/doom-horizon-theme.el
This commit fixes issue #486.
For detailed screenshots (before-and-after), please kindly refer to the thread. Cheers!
=> Fix doom-horizon's brigher comment readability issues (#486)

themes/doom-zenburn-theme.el
Visual enhancements include company-mode, highlight-symbol, and highlight-thing
=> Fix Zenburn inherit face bug + minor visual enhancements

themes/doom-gruvbox-theme.el
=> Fix search and replace decoration in doom-gruvbox

doom-themes-ext-neotree.el
Makes compatible with latest Emacs 28 changes
> Please follow these steps before submitting your PR
>
> - [ ] Include before and after screenshots if your change is visual
> - [ ] Please explain what the PR does and why
> - [ ] List and link any packages you are adding support for
> - [ ] Delete this template before submitting
>
> Thank you for contributing to our theme pack!
=> Add version to define-obsolete-variable-alias

themes/doom-one-light-theme.el
=> doom-one-light: Theme `selectrum-current-candidate'

README.md
As suggested in #503 here's a bit of blurb to help emacs users without GUI compiled in.
How does it look? Please let me know how can I improve the wording.
p.s. Emacs did its thing removing some stray spaces
p.p.s. I'm not here for the tshirt :smile:
=> How to enable 24bit colors on a non graphic shell

README.md
Please explain what the PR does and why:
It fixes the typos so people aren't confused on what themes are available
=> Update README.md to fix typos in ayu themes

themes/doom-ir-black-theme.el
I took the colors from the well-known `ir_black` palette. Unfortunately, this was a while ago, so the structure may need some cleanup. Let me know what needs to be done.
=> [RFC] IR Black

doom-themes-base.el
> Please follow these steps before submitting your PR
>
> - [ ] Include before and after screenshots if your change is visual
> - [ ] Please explain what the PR does and why
> - [ ] List and link any packages you are adding support for
> - [ ] Delete this template before submitting
>
> Thank you for contributing to our theme pack!
=> Add corfu faces

README.md
A in-page link in README.md was broken.
-----
=> docs: fix in-page link in README

themes/doom-challenger-deep-theme.el
Looks like #753 is to be fixed on a per theme basis. Here is the fix for challenger-deep.
-----
=> fix(challenger-deep): 'nil value is invalid' warnings

extensions/doom-themes-ext-org.el
The function name was wrong.
-----
=> fix(ext-org): function name in commentary

doom-themes-base.el
=> Evaluate `base5` in `cider-result-overlay-face`'s `:box`
