doomemacs/themes

doom-one-theme.el
Before:
After:
tbh I don’t actually care about `message-header-name` but about `mu4e-header-key-face` which inherits from it. Setting `message-header-name` should help other mail clients but I haven’t tested any.
=> Change message-header-name face

doom-one-theme.el
Added some colors for Elscreen. I named the variables `tab-unfocused-bg/fg` so that it can be reused for other tab libraries, since elscreen isn't the only one. Here's an image of how it looks:
=> NEW add elscreen

doom-one-theme.el
This pr fixes the colors that [tabbar](https://melpa.org/#/tabbar) uses for doom-one. More customization is needed to make it look better (spacing in the tabs, changing the default ugly icons, etc.) but I don't know if these belong in doom-one.
Here's a screenshot:
=> Basic support for tabbar

doom-one-theme.el
Without this it’s sadly almost unreadable. I don’t really care which color in particular is chosen as long as it’s readable so if you have any better suggestions I’m all ears.
*before*
*after*
=> Support which-function-mode

doom-themes-common.el
Change the foreground of swiper matches to black to allow for better contrast and visibility.
Before:
After:
After (molokai):
=> change forground of swiper matches to black for better contrast

doom-one-theme.el
I think this looks nicer, so I added an option. 
Screenshot:
=> Add doom-one-padded-modeline option

doom-themes-common.el
My attempt to add faces for the language server protocol [1], which currently are:
- lsp-face-highlight-textual
"textual occurances of symbols."
default: yellow background
- lsp-face-hightlight-read
"highlighting symbols being read."
default: red background
- lsp-face-hightlight-write
"highlighting symbols being written to."
default: green background
[1] https://github.com/emacs-lsp/lsp-mode
The yellow looked completely out of place so I used the colors use for incremental search; if you have a better idea for what color, I don't mind. ;)
NB: there seems to a type in hightlight for -read, -write. I have opened an upstream issue emacs-lsp/lsp-mode#89 about it, so these might change. Also I just used the same colors for read and write, which might also not be the best, but it is a start I …
=> Add lsp faces

doom-themes-common.el
The typos (hightlight) got fixed upstream. So we need to adapt.
I was tempted to change the faces for -read and -write to the something like magit-diff-added-highlight and magit-diff-removed-highlight, since the original color for the faces were green and red, but I couldnt find a way to trigger the faces so I left them as is for now.
=> Sync lsp faces names with upstream

doom-nova-theme.el
This PR adds the basic color scheme for new theme based on [Nova](https://trevordmiller.com/projects/nova) as discussed in #60.
I've marked some of the lines with a **TODO set correct color** where I don't know what color to use. I've used this values as a guide for creating the file https://github.com/trevordmiller/nova-colors/blob/master/src/index.js.
This is the WIP result, which doesn't look very good... 🤔 
I hope it helps as a starting point for creating another awesome doom's version 🤘
=> Nova theme basic colors

doom-themes-common.el
=> Theme whitespace-{empty,space} using base3

doom-themes-common.el
Brings back dark background for transactions under the cursor. In one of the refactoring it got brighter.
=> [ledger-mode] Nicer active transaction background

doom-themes-common.el
ansi-color expects this type of vector ["color1" "color2" "color3" ...]
(vector sequence) returns [(seq uen ce)] while
(vconcat (sequence)) returns [seq uen ce]
=> Fix: ansi-color-names-vector: vector -> vconcat

themes/doom-one-theme.el
Atom uses yellow which is too similar to green, but orange is distinct and looks better than gray.
=> Change vc-modified to orange

doom-themes.el
Using `doom-themes-set-faces` causes this warning:
Symbol’s function definition is void: doom-themes--build-face
Moving the require to top level removes this warning.
=> Require common in top level to avoid warnings

themes/doom-one-light-theme.el
1. Highlight-Line
2. Selected on "is somewhat confused"
3. After-Fix
=> for more obvious color difference on hl-light and selected text

themes/doom-one-light-theme.el
Cannot see the selected lines of code blocks in markdown mode. I make this change to visualize it.
=> make it clear when visualize (in visual mode) markdown code block

themes/doom-one-light-theme.el
Base3 is too dark for markdown, so I put base1 here. While for org block, I think it should be consistent with markdown block.
This is how it looks in doom emacs with `solaire-mode`.
I tweaked some faces with black background as default. It looks better now.
Thanks!
=> Face tweaks for markdown and org block, helm, web-mode, wgrep

themes/doom-one-light-theme.el
Just a slight modification. I use Spacemacs and its built-in theme has differences between `ediff-current-diff-*` faces. So I modified them in doom-one-light theme.
Here are what these faces look like.
=> Add ediff faces and org quote background

themes/doom-molokai-theme.el, themes/doom-nova-theme.el, themes/doom-one-light-theme.el, themes/doom-one-theme.el, themes/doom-peacock-theme.el, themes/doom-solarized-light-theme.el, themes/doom-spacegrey-theme.el, themes/doom-tomorrow-night-theme.el, themes/doom-vibrant-theme.el
`vertical-bar` was set to a color too close to the background, making it essentially invisible in most dark themes. It seems like `(doom-lighten bg 0.1)` is a good choice for dark themes, and correspondingly `(doom-darken bg 0.1)` for light themes.
=> Change vertical-bar so that window-divider stands out.

themes/doom-tomorrow-day-theme.el
Hello. I'm no theme expert, but I decided to try to scratch my own itch re: #143 
1. I copied the existing themes/doom-tomorrow-night-theme.el to themes/doom-tomorrow-day-theme.el
2. Substituted the colors from https://github.com/ChrisKempson/Tomorrow-Theme
3. Changed all the bg*, base*, fg* gui values to their RGB compliments, looked up the websafe versions of the compliments for 256 values, and looked up the 16 color names. Also changed all ```doom-lighten``` to ```doom-darken``` and vice-versa.
I hope that's how you do this. It looks okay to me.
Cheers.
=> Add doom-tomorrow-day.el

themes/doom-city-lights-theme.el, themes/doom-nord-theme.el
1. Added `doom-nord-region-highlight` variable to specify the region highlight style: "forest", "snowstorm" and default
2. Adjust modeline-bright so that they looks more natural
3. Adjust specific faces (City Lights `org-block`)
=> Adjust City Lights and Nord color to comply with specification

doom-themes-common.el
I kept the bold for arrays and bold/italic for hashes, but removed the jarring backgrounds.
Old:
New:
=> Add cperl faces

themes/doom-one-light-theme.el
The original background is so dark that I cannot even recognize the line selection.
I make the background brighter like this.
=> Add: update posframe faces

doom-themes.el, themes/doom-challenger-deep-theme.el, themes/doom-city-lights-theme.el, themes/doom-dracula-theme.el, themes/doom-molokai-theme.el, themes/doom-nord-light-theme.el, themes/doom-nord-theme.el, themes/doom-nova-theme.el, themes/doom-one-light-theme.el, themes/doom-one-theme.el, themes/doom-peacock-theme.el, themes/doom-solarized-light-theme.el, themes/doom-spacegrey-theme.el, themes/doom-tomorrow-day-theme.el, themes/doom-tomorrow-night-theme.el, themes/doom-vibrant-theme.el
Serves as the default value for the padded-modeline variable for themes that
have one
=> Add doom-themes-padded-modeline custom var

themes/doom-nord-light-theme.el
Use a darker bg-alt for doom-nord-light
=> Fix: doom-nord-light bg-alt

themes/doom-spacegrey-theme.el
I was getting a lot of messages about not being able to load the color.  It was just missing a hashmark in front of the hex code 😄 .  These themes are great btw!
=> Fix spacegrey color definition.

themes/doom-one-light-theme.el
Just make lsp highlight face be consistent. Since `ivy-posframe-cursor` now inherit from cursor face, we can remove it now.
Thanks 😃
=> A few updates for lsp

doom-themes-treemacs.el
This will allow someone to disable the custom treemacs icons without disabling the other nice things doom-themes does for treemacs.
=> Put the treemacs icons behind a variable

doom-themes-common.el
This was changed in this commit: https://github.com/magit/magit/commit/3718544b55b10b4e78a31ba4044fbaa9f2e9e2e1
=> Change git-commit-note to git-commit-keyword

doom-themes-common.el
These faces are used when invoking `` C-c ` `` to display the list of errors from a TeX-mode buffer.  I modeled them after the compilation-mode faces, but do not want to inherit since `compile.el` will not necessarily be loaded.
=> Add TeX-error-description-* faces

themes/doom-one-light-theme.el
instead fallback to the one set from doom-themes-common
otherwise in buffers like treemacs it results in the same background color as hl-line face
=> one-light: don't set solaire-hl-line-face

doom-themes-treemacs.el
`treemacs-icon-closed-png` inherits attributes from `font-lock-doc-face`, which may be italicized in some themes, e.g. `doom-one-light`. This causes the closed folder icon to appear slanted in those themes.
This commit explicitly sets the face to `:slant normal`, so that closed folders are never italicized/slanted.
For example, doom-one-light treemacs _before_:
And _after_ (note the folders are no longer slanted):
=> Set treemacs closed folder icon to not slanted

doom-themes-treemacs.el
Not sure if this was intentional, but tags in non-variable pitch face look out of place when everything else is variable-pitched.
=> Register treemacs-tags-face to also get variable-pitched

doom-themes-ext-org.el
If not using MELPA for doom-themes, require didn't work properly with the org-mode extension because of mismatching filename and `(provide)`.
=> Fix a bug with mismatching (provide) and filename

themes/doom-tomorrow-night-theme.el
I have solved my problem in issue #301 by changing the value of fg-alt from being darkened by 0.6 to 0.4.
Here's a quick before-and-after: **Notice the tabs font colors**
=> Tomorrow-Night: change fg-alt darken to increase visibility

README.md, doom-themes-ext-treemacs.el
Given it's a little heavy change, I decided it was better to assign a reviewer. This change adds a `doom-themes-treemacs-color-icons` flag that when true, displays a more colorful Treemacs theme than the original, minimal atom inspired implementation by Henrik.
=> Treemacs colorful icon theme

doom-themes-base.el
Related with https://github.com/hlissner/emacs-doom-themes/pull/325.
Note that themes `palenight` and `moonlight` already set their own faces for `man`.
=> Add: common faces for man and woman

doom-themes-ext-visual-bell.el
Use `face-remap.el` rather than modifying `face-remapping-alist` directly.
Long explanation:
I was having modelines stuck in inverse video, and developed a hunch that it was something between flycheck-color-mode-line and doom-theme. I found some files that would make it happen consistently and here is what appears to have happened:
1. I open the file and something triggers the bell (in this case `company-clang` complaining it couldn't find the executable, but that's not important).
2. `doom-themes-visual-bell-fn` adds a face remapping and stores the old remapping list.
3. Flycheck finishes, sets the state and flycheck-color-mode-line adds a remapping using `face-remap-add-relative`.
4. `face-remap-add-relative` makes `face-remapping-alist` buffer local and modifies it.
5. The timer …
=> Use face-remap in visual bell

doom-themes.el, themes/doom-Iosvkem-theme.el, themes/doom-challenger-deep-theme.el, themes/doom-city-lights-theme.el, themes/doom-dracula-theme.el, themes/doom-fairy-floss-theme.el, themes/doom-gruvbox-theme.el, themes/doom-molokai-theme.el, themes/doom-moonlight-theme.el, themes/doom-nord-light-theme.el, themes/doom-nord-theme.el, themes/doom-nova-theme.el, themes/doom-one-light-theme.el, themes/doom-one-theme.el, themes/doom-opera-light-theme.el, themes/doom-opera-theme.el, themes/doom-outrun-electric-theme.el, themes/doom-palenight-theme.el, themes/doom-peacock-theme.el, themes/doom-solarized-dark-theme.el, themes/doom-solarized-light-theme.el, themes/doom-sourcerer-theme.el, themes/doom-spacegrey-theme.el, themes/doom-tomorrow-day-theme.el, themes/doom-tomorrow-night-theme.el, themes/doom-vibrant-theme.el, themes/doom-wilmersdorf-theme.el
About `doom-themes-padded-modeline` and other `padded-modeline` suffixed customizable variables, I think `:type '(or integer boolean)` should be `:type '(choice integer boolean)`.
Elisp manual: https://www.gnu.org/software/emacs/manual/html_node/elisp/Composite-Types.html#Composite-Types
=> Fix customization type of padded-modeline.

themes/doom-city-lights-theme.el
Using city-lights for a while now and there is a face that bothers me which is the magit hunk heading. I've changed the face to use less intrusive colors, and it works better for me. 
What are your thoughts about this change? Here is a snapshot from the Magit log for illustration of how it looks, both highlight and normal states:
current:
modified:
=> Mod: magit hunk heading face for city-lights

themes/doom-gruvbox-theme.el
=> Gruvbox: Remove background from org ellipses 

themes/doom-acario-light-theme.el
`fixed-pitch-serif-face` doesn't exist and causes error while exporting org to html.
=> fixed-pitch-serif-face -> fixed-pitch-serif

themes/doom-gruvbox-theme.el
=> add red background on gruvbox: ediff-current

themes/doom-gruvbox-theme.el
covers magit primary display scheme.
btw, how do I align multiple columns by `:`?
before:
after:
=> gruvbox magit main view colors

themes/doom-material-theme.el
Closes #318.
Adds initial material theme, which is mostly the same as palenight theme with default material background.
(Future plans - configurable accent color, other material varations)
=> add material theme

README.md
The reference to `doom-nord` seems to have got lost during the reshuffle here: https://github.com/hlissner/emacs-doom-themes/commit/373aa8c03342ee26e407403bc2b3b1c3dc5757f3#diff-04c6e90faac2675aa89e2176d2eec7d8
This PR adds it back.
=> Re-add the `doom-nord` theme in readme

themes/doom-acario-dark-theme.el, themes/doom-acario-light-theme.el
No change is made, this is just to help navigation within the file with outline/outshine enabled editors.
=> Use outline comments to organize acario themes

doom-themes-base.el
By making use of the new `:extend` keyword, we can make sure that the background highlight of the current ivy match doesn't end abruptly with the last word.
I've tested this small addition on my machine and it works as intended. Please consider the pull request. Cheers!
=> Extend the ivy-current-match background highlight to full line width

doom-themes-base.el
Small change, makes it more clear which source one is looking at in a helm selection.
=> Increase salience of `helm-source-header`

themes/doom-challenger-deep-theme.el
I'm overall pleased with the challenger-deep theme, but the default styling for org-link isn't outstanding enough.
Before:
After:
=> Add org-link styling for doom-challenger-deep

README.md, doom-themes.el, themes/doom-manegarm-theme.el
Manegarm is a dark theme with an autumn-inspired color palette.
I wanted to create a dark theme that uses a non-white or not-very-light color for its foreground. After finally having settled for a darker tone of green, the rest of the color palette was already mostly complete.
I think it might be the first dark doom theme that uses a "non-standard" foreground color.
The finalized color palette reminded me a lot of album covers of some bands that I used to listen to. The one that stuck out the most was the Månegarm album "Vredens Tid" - hence the name.
For `org-mode`, I used some of the colors in the palette that are not very present elsewhere. I just need the org headers to stand out a bit more.
Now I'm primarily looking for feedback. At the moment, I don't have that much time, so I'm …
=> WIP: Add doom-manegarm theme

doom-themes-base.el
This sets up the background for lsp-ui-doc to be the same as tooltip.  This matches how the company-tooltip looks.
=> Set lsp-ui-doc-background to inherit from tooltip

themes/doom-horizon-theme.el
Darkening the default foreground by 0.2 is actually still brighter than lightening the background by 0.2. Hence the former should be used when the modeline is active, and the latter for inactive.
=> [Horizon] Swap modeline active/inactive face

themes/doom-dracula-theme.el
This better matches Dracula's [official `font-lock-type-face`](https://github.com/dracula/emacs/blob/master/dracula-theme.el#L77). I realize this could have been overridden per-mode, but I can't find the current `blue`'s hex color anywhere in [Dracula's palette](https://github.com/dracula/dracula-theme#color-palette) and it's always stood out to me as not quite fitting the rest of the theme.
The overrides for `highlight-quoted-*` are also to better match the official theme.
`dracula`:
`doom-dracula` (current):
`doom-dracula` (with these changes):
=> Change Dracula's "type" color to violet

README.md, themes/doom-monokai-pro-theme.el
I'm pretty new to the emacs community, but started using Doom recently (introduced to it by Doom Themes) and have loved it. I created these three themes for myself that I rotate through depending on my mood. Wondering if any of these are worth adding in? 
edit: removed other two themes
=> Add New Monokai Pro Theme

README.md, doom-themes.el, themes/doom-rouge-theme.el
This is my first attempt at fully porting a theme. This is in reference to https://github.com/hlissner/emacs-doom-themes/issues/417
NOTE: this was ported from the nord theme as a base. Would have likely been better to start from the material theme. There might be a few colors left over from the nord theme that I was never able to surface through my workflows.
Variations from VSCode theme:
* Constants are 'orange' in this rather then 'yellow'. I used ruby as a base and it stayed closer to the overall look since constants and module/class definitions use a shared base.
I have only tested this with a few language modes (ruby elisp go). None of them are 100% matches. This is largely due to VSCode having more fine grained control over 'faces' in its supported languages
=> Add theme rouge

themes/doom-spacegrey-theme.el
The code in this change set fixes #405 (sets `org-hide`) to `bg`
- Tested with both `solaire-mode` on and off
=> [405][spacegray] Fix issues with visible asterisks

themes/doom-acario-dark-theme.el, themes/doom-manegarm-theme.el
I encountered an error while trying out the themes.
Seems that the face should be `fixed-pitch-serif` instead of `fixed-pitch-serif-face`.
Only the file `doom-acario-light-theme.el` has `fixed-pitch-serif` instead of `fixed-pitch-serif-face`, and I was able to use the theme successfully.
=> Fix fixed-pitch-serif face

themes/doom-monokai-pro-theme.el
base4 is hard to distinguish from default background.
use base5 instead
screenshot for base4:
screenshot for base5:
=> Change background of selection

doom-themes-base.el
Used to show information about symbols on the side.
=> Add lsp-ui-sideline-symbol-info face

themes/doom-gruvbox-theme.el, themes/doom-one-theme.el
Since latex' math-mode and keywords share the same color, I changed the one of math-mode to green (which IMO looks pretty neat).
So far quoted elisp symbols and function names shared the same color. I made use of dark-cyan to make them distinguishable.
The headers of a mail opened in view mode look pretty uniform. I spiced up the keys with red, to make it more readable.
This one is a bit more opinionated. Latex' math-mode uses blue as its face. I think it doesn't really complement the pastel look of the theme, and thus changed it  to dark-cyan.
=> Minor face improvements for doom-one and doom-gruvbox

README.md, doom-themes.el, themes/doom-henna-theme.el
This is my first attempt at converting a theme, and I echo the comments by @JordanFaust [here](https://github.com/hlissner/emacs-doom-themes/pull/418#issue-383952353) about this not being a 100% 1 to 1 match to the vscode original. 
- fixes: #426 
- **Base theme used**: `doom-one`
**Todo**
I only tested in a couple modes, here is a checklist..
screenshots below showcases some of the areas I focused on.
**general**
`magit`
`python-mode`
`web-mode`
`cpp-mode` 
`org`
`which-key`
`search`
`splash`
=> [WIP] Add Henna Theme

README.md
Links for doom-one-light and doom-vibrant had a trailing '-wip' whereas the targets didn't.
=> Fix internal README links for one-light & vibrant

themes/doom-solarized-light-theme.el
Mail header and cited text is barely visible, the suggested colours are better.
Thanks.
=> Fix almost invisible faces in notmuch mail (doom-solarized)

themes/doom-monokai-pro-theme.el, themes/doom-monokai-spectrum-theme.el
I'm not sure if a PR like this is acceptable, given that [deadgrep](https://github.com/Wilfred/deadgrep) isn't included in doom emacs by default, but I'm trying my luck!
P.S. deadgrep is awesome! I'd be keen to write a module for it.
=> Add deadgrep-match-face to monokai pro and spectrum themes

doom-themes-base.el
=> doom-themes-base: separate header-line and mode-line

themes/doom-gruvbox-light-theme.el, themes/doom-gruvbox-theme.el
Added contrast options hard/soft for gruvbox dark, fixed documentation typo for gruvbox light, and tweaked a few other minor details (mostly colour improvements and naming refactors.).
=> Add hard/soft contrast options for gruvbox dark

themes/doom-zenburn-theme.el
Adds the `zenburn` theme. 
`zenburn` has a bunch of extra colors, which I then used to override some of (maybe alot of) doom defaults for certain modes. Not sure if this was the best way to go about this, any feedback is welcome.
- fixes #415 
Other screenshots
`org-mode`
`python-mode`
`js2-mode`
`web-mode`
`typescript-mode`
`which-key`
=> [-] Add zenburn theme

doom-themes-base.el
This small commit targeting doom-base makes sure that all **web-mode json-keys and json-context will be styled as strings** (following the design guideline used by Visual Studio Code).
=> [doom-base] Add web-mode support for json-keys and context

themes/doom-old-hope-theme.el
Based off of [An Old Hope Syntax](https://github.com/jesseleite/an-old-hope-syntax-atom)
Screens demonstrating a mix of different languages:
=> Add:  doom-old-hope-theme.el

themes/doom-spacegrey-theme.el
The setting only applied to doc comments, which are a small subset of actual comments.
=> Fix spacegrey brighter comment color

themes/doom-flatwhite-theme.el
This is a port of [flatwhite-syntax](https://github.com/biletskyy/flatwhite-syntax), by Dmitry Biletskyy.
Dashboard:
With an Ivy menu:
Which Key:
Python:
With Swiper:
Elisp:
Javascript:
Clojure:
Racket:
Ruby:
Dired:
Markdown:
Magit:
String search (`int`, in this case):
- This theme goes a little against-the-grain, as it colors the background behind the text to achieve the desired highlighting. As a result, this theme file is quite a bit longer than most others, with more explicit face definitions. 
- All the modes I've tested work pretty well, but I'm open to feedback on particular choices made.
=> Add doom-flatwhite theme

doom-themes-base.el
Because red is the error/invalid link face, and I don't like thinking my perfectly-fine references are invalid.
=> Change org-ref ref face to teal

themes/doom-gruvbox-light-theme.el
- fixes the cursor being white after startup and black after reloading the theme 
- cursor is now grey, as in the [original gruvbox light](https://github.com/morhetz/gruvbox#light-mode) 
~~- the black cursor can be brought back by setting `doom-gruvbox-light-darker-cursor` to `t`~~
- in the [original](https://github.com/morhetz/gruvbox#light-mode) version, line numbers have no special background
=> doom-gruvbox-light: fix cursor bug, remove line numbers background

themes/doom-plain-theme.el
Before:
After:
This fixes visibility issues with org babel blocks' indicators.
=> Fix org source block indicators' visibility for doom-plain

themes/doom-solarized-dark-theme.el
This is in line with solarized-light, which is more readable imho.
=> solarized-dark: change variables to blue

themes/doom-flatwhite-theme.el
As discussed in https://github.com/hlissner/emacs-doom-themes/pull/514
The original [flatwhite-syntax](https://github.com/biletskyy/flatwhite-syntax) theme for Atom does not highlight variable names. However, the [Sublime Text](https://github.com/Willamin/flatwhite) version of the theme does highlight variable names in blue.
This change adds a blue highlight to variable names, with a config variable (`doom-flatwhite-no-highlight-variables`) to turn the highlight off, for those who prefer the original theme.
This also changes the highlight color for keywords in `racket` and `clojure` (for example: `#:stuff` and `:stuff` respectively) from blue to orange, to better fit with the new usage of blue as the variable name color.
Or, with `(setq doom-flatwhite-no-highlight-variables t)`
=> Flatwhite: Add blue highlight to variable names

themes/doom-zenburn-theme.el
`doom-zenburn.el` file left out a single quote on two `:weight` attributes in the helm section. This fixes the typo and restores the theme's ability to be loaded and unloaded. Without the fix users cannot load new themes after loading doom-zenburn.
=> Fix doom-zenburn.el typo

themes/doom-monokai-pro-theme.el
A small typo in the variable name in `doom-monokai-pro-theme.el`.
=> Fix variable typo

doom-themes-base.el
This themes faces in Artur Malabarba's `smart-mode-line` package: https://github.com/Malabarba/smart-mode-line/
Without this patch, it looks like this: 
Thanks for your work on doom-themes.
=> Add: smart-mode-line (sml/) faces

README.md, themes/doom-homage-black-theme.el, themes/doom-homage-white-theme.el
These themes were evolving for several years already in my personal
emacs configuration and finally moved to doom-themes framework. Main
idea of these themes is to reduce amount of colours to bare minimum, yet
preserve bright and sharp look of main elements.
I took doom-one and doom-one-light themes as an initial carcass for this
transformation.
White theme using palette inspired by various editors from 2000s, with a
lot of inspiration from eziam theme (thblt/eziam-theme-emacs) and tao
theme (11111000000/tao-theme-emacs).
Black theme is (manually) inverted white theme with a focus of having
pitch-black backgrounds. I also incorporated several ideas from jbeans
theme (synic/jbeans-emacs).
---
I used slightly modified eziam theme test files and my personal org-mode buffers to produce …
=> Add new themes: homage-white and homage-black

themes/doom-plain-dark-theme.el, themes/doom-plain-theme.el
Motivation for this change is supplying a dark theme for plain-theme as well as improving the current plain theme.
This PR adds support for plain-dark-theme which is the sister theme complement to the existing plain theme. Use of italics according to the [original plain theme](https://github.com/gko/plain/) has been adapted, especially for org-mode headers. Italics fit into the minimalistic theme approach better than the current bold ligatures as they provide a rather subtle way of emphasis beside colors which this theme naturally lack.  
<details><summary>Code</summary>
<p>
</details>
</p>
<details><summary>Org</summary>
<p>
</details>
</p>
=> Update plain-theme and add plain-dark-theme

doom-themes-base.el
Supercedes https://github.com/hlissner/emacs-doom-themes/pull/569. Didn't realize I had included the new high contrast theme in the other PR. I don't want to remove it from my fork's master branch, so I've just opened this new PR from a different branch.
Edit: typo (wrong PR)
=> Theme selectrum in doom-themes-base

doom-themes-base.el
Fixes https://github.com/hlissner/emacs-doom-themes/issues/573 and will be forwards-compatible once https://github.com/raxod502/selectrum/issues/364 is resolved.
=> Remove theming for selectrum-*-highlight

themes/doom-gruvbox-theme.el
The current doom-gruvbox theme has  numerous deviations from the original theme which ends up making it look different from each other. This PR aims to make gruvbox look more closer to the original theme by using the [same choice of colors](https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim) where applicable.
This also includes some changes to make gruvbox look better with Solaire mode enabled.
- use the same colors as upstream where applicable
- make `bg-alt` darker than `bg`
- set modeline colors for solaire mode
=> gruvbox-dark: make it closer to the orignal plus solaire mode fixes

doom-themes-base.el
Adds faces added by `terraform-mode` to `doom-themes-base.el`.
=> Add terraform-mode faces

themes/doom-dracula-theme.el
The value passed to `doom-lighten` function was incorrectly passed as variable reference `'magenta` instead of `magenta`.
This caused the color for `variables` to not render during startup but for some reason it worked if you did a `reload-theme (SPC h r t)`. See issue #572.
I have tested that this works in my fork.
=> dracula-theme: Fix rendering of variable color

themes/doom-one-light-theme.el
Set lsp-headerline-breadcrumb-separator-face foreground to green to resolve issue where separates do not appear for lsp-headerline-breadcrumb-mode for doom-one-light theme.
**Before**
**After**
=> Resolved issue where breadcrumb separators do not appear

doom-themes-ext-treemacs.el
https://github.com/domtronn/all-the-icons.el/pull/228 separates a large portion of extension-handling regexes to a separate extension list. This PR removes references to the to-be variable all-the-icons-icon-alist.
And coincidently simplifies some of doom-themes' code by removing `doom-themes--get-treemacs-extensions`!
=> Adapt treemacs theme generation to all-the-icons#228

themes/doom-horizon-theme.el
Make it closer to the original theme and improve aesthetic.
On the left is Horizon on Visual Studio Code, the upper right is on Emacs, before, the lower one is also Emacs, but after brightening.
(Notice current line on each).
=> doom-horizon: make line-number-current-line closer to the original

themes/doom-ephemeral-theme.el, themes/doom-plain-theme.el
Fixes face issues for doom ephemeral where mailing lists in notmuch have illegible font colour, and fixes ivy frame in doom-plain and org-src blocks.
Relevant screenshots:
Before:
After:
Sorry for the commit mess, I was learning git and magit usage while creating this PR, hope it isn't a problem.
=> Fix faces for doom-plain and doom-ephemeral themes

README.md, themes/doom-1337-theme.el
This is a port of 1337 theme based on [microsoft/vscode-themes/1337](https://github.com/microsoft/vscode-themes/tree/master/1337)
The original 1337 theme in VSCode
The doom-1337 theme in Emacs
=> Add new theme: doom-1337

README.md, themes/doom-badger-theme.el
Here is my attempt at the `badger` theme. I took some liberties when it came to `treemacs` and `web-mode`
* **Base theme**: `doom-one`
* fixes #113 
**Notes**
I noticed the `badger` sets `variables` to `salmon` ([here](https://github.com/ccann/badger-theme/blob/master/badger-theme.el#L139)) and `builtints` as `violet` ([here](https://github.com/ccann/badger-theme/blob/master/badger-theme.el#L145)) yet the [screenshot](https://github.com/ccann/badger-theme/blob/master/img/python-preview.png) has them reversed, so I went with the screenshot. This can be reversed, if needed ofc.
**TODO**
Checklist of what I tested so far
screenshots
`python-mode`
`web-mode`
`which-key`
`typescript`
`js2-mode`
`magit`
`search`
`mode-line`
=> [-] Add Badger theme

README.md, themes/doom-solarized-dark-high-contrast-theme.el
New theme, doom-solarized-dark-high-contrast, based on existing doom-solarized-dark and solarized-dark-high-contrast-theme from https://github.com/bbatsov/solarized-emacs.
Screenshots:
Let me know if you'd like any more!
=> New theme doom-solarized-dark-high-contrast

themes/doom-one-light-theme.el
fix `Symbol’s value as variable is void: doom-modeline-brighter-modeline`
=> doom-one-light: use correct symbol name

themes/doom-molokai-theme.el, themes/doom-monokai-classic-theme.el
Very simple change, did not follow the template for that reason.
3f09923 forced git-gutter faces to follow vc-modified, but in a few themes, vc-modified was (mistakenly I guess) set to base4 (a kind of black), hence I am modifying vc-modified to cyan.
Feel free to ask any question.
Best,
Aymeric
=> molokai & monokai-classic : set vc-modified to cyan after 3f09923

themes/doom-nova-theme.el
- trim extra whitespace
- reorder code position and align right parenthesis
=> doom-nova: clean up codes

themes/doom-oceanic-next-theme.el
Improved readability when using magit.
**Before**:
**After**:
=> Updated doom-oceanic-next theme.

themes/doom-horizon-theme.el
Before: on the left, after: on the right
Original theme (referenced: [Horizon theme](https://horizontheme.netlify.app/) )
Make comments italic, like the original.
Edit: removed the PR template.
=> doom-horizon: make comments' slant italic

themes/doom-acario-dark-theme.el, themes/doom-acario-light-theme.el
No screenshot because loading the theme simply errors if the bright modeline custom is set.
=> [acario-dark] Fix modeline-bg when brighter

doom-themes-base.el, themes/doom-one-light-theme.el
This adds support for [vertico](https://github.com/minad/vertico); specifically highlighting the current selected candidate via the `vertico-current` face.
I simply copy-and-pasted the definitions for `selectrum`, which `vertico` is basically a drop-in replacement for.
The result, therefore, as with `selectrum`, is a more subtle highlighting:
Before:
=> Add vertico-current definition

themes/doom-vibrant-theme.el
Theme: doom-vibrant color `bg` and `base3` are very similar, leading to org-blocks being hard to distinguish from background.
`((bg         '("#242730" "black"       "black" ))`
`(base3      '("#23272e" "#262626"     "brightblack" ))`
Screenshot of before: Very hard to distinguish color `bg` from color `base3`
Screenshot of after: Easier distinguish color `bg` from color `(doom-darken base3 0.1)`
=> org-block darkened as bg and base3 are very alike

doom-themes-base.el
Now that https://github.com/minad/marginalia/pull/91 has been merged, Marginalia has new faces to do exactly the same thing a `diredfl` currently does with file attributes. I.e. this:
So, here's a PR that just copies the `diredfl` face information, just for the incoming Marginalia faces.
=> Add marginalia file privilege faces

doom-themes-base.el
This adds support for the four (orderless)[https://github.com/oantolin/orderless] faces, seen below
Unfortunately, this patch makes my Emacs segfault, so I can't easily provide an after image. If anyone has any idea what's going on *please* let me know. Full error: http://ix.io/3u7E
=> Add orderless faces

doom-themes-base.el
This defaults to `:inherit completions-annotations`, which is `(italic shadow)`. However, for *documentation* `font-lock-doc-face` would seem more sensible.
Default:
With this patch:
=> Add marginalia documentation face

themes/doom-horizon-theme.el
change orderless-match-face-1 from magenta to red
---
The magenta stands out too little from the background imo.
Before:
After:
=> doom-horizon: better orderless face

doom-themes-base.el
Before
After
Currently, `marginalia-numbers` inherits from `font-lock-constant-face`, but we have a colour for numbers! Marginalia though is over-eager with the inheriting from `marginali-numbers` though, so we set the list and size style to be unaffected, i.e. violet.
Before
After
=> 3 for 1: Add org-cite faces, fade diredfl dash, marginalia numbers

themes/doom-gruvbox-theme.el
Ok, after my previous PR (#614) , I realized that my doom-themes was out-of-date, and everything was looking broken so I decided to make my theme again from 0. The images look the same ( the look of my changes didn't change ), so it still seems like the images in #614.
I decided to break down my changes in  5 parts so you can I understand better what I changed: 
- **Added some colors**, I added 2 more colors based on morhetz's gruvbox theme (vim) which are a blue and black.
-  **Changed face categories**, Actually I changed functions, methods, operators, and type. But I changed them because they looked cool, it's not necessary to keep these.
- **Changed modeline's face**, In original doom-gruvbox the modeline looks like this:
It's actually hard to recognize in which window you are + the …
=> Add My Doom Gruvbox (fix)

README.md, doom-themes.el, themes/doom-tokyo-night-theme.el
A dark theme based on [Tokyo Night](https://github.com/enkia/tokyo-night-vscode-theme).
=> Add Tokyo Night theme.

themes/doom-earl-grey-theme.el
This PR adds an implementation of the [Earl Grey](https://earl-grey.halt.wtf/) theme. (In fact, I used doom-themes to develop this theme, so this is the _original_ implementation of Earl Grey!).
=> Add Earl Grey theme

README.md, doom-themes.el, themes/doom-material-dark-theme.el
Material Dark Theme
As close as I could get it in an afternoon to the theme it's inspired by: https://github.com/xrei/material-dark-vscode
This theme is a lot like the included material theme. Thanks go to @tam5 for providing the source that was my starting point.
The theme features an overall darker background and makes broader use of red/yellow/green.
=> Add Material Dark Theme

README.md, doom-themes.el, themes/doom-meltbus-theme.el
I would like to contribute this (mostly) monochromatic theme, because there was no suitable one, yet.
It does not completely avoid the use of colour but tries to be monochromatic in the everyday coding / text-writing use-case. Colours, where used, and the shading is subtil and the default foreground colour is not white, so there is room for highlighting. This was mostly done to avoid distraction/confusion by too much colour.
It provides two customisation variables:
- doom-meltbus-hl-line :: to disable hl-line drawn as an underline
- doom-meltbus-uniform-font-size :: to switch from variably sized org-mode headings to uniform but shaded headings
Colour is used for:
- distinguishing states (diff, search, vi-modes, flycheck ...)
- highlighting interactive elements (enabled flags, buttons, …
=> doom-meltbus: A dark (mostly) monochromatic theme

themes/doom-gruvbox-theme.el
Hey,
I use `doom-gruvbox-dark`, and https://github.com/doomemacs/themes/pull/616 recently improved the theme. I think that most changes were really good (specially the modeline ones), but I dislike the new code faces. The main reason is how _jumpy_ the new `my_blue` is. I don't think it blends well with the rest of the colorscheme and it is a significant deviation from [the original colorscheme](https://github.com/morhetz/gruvbox/wiki/Gallery). 
From @ItsNilDev 's pr:
> Changed face categories, Actually I changed functions, methods, operators, and type. But I changed them because they looked cool, it's not necessary to keep these.
Current theme:
Old/reverted code faces:
I understand that this is quite subjective, but I feel like most users would prefer the theme that more closely …
=> Revert gruvbox-dark code-font changes from #616

themes/doom-tokyo-night-theme.el
Fixes the illegible colour of org-blocks that stands out and causes issues when reading commented/greyed out characters.
=> Fix illegible org blocks: doom-tokyo-night

extensions/doom-themes-ext-visual-bell.el
Since emacs 29 (the current git master), the `mode-line` face is the parent of the new face `mode-line-active` and `mode-line-inactive`.  For remapping purposes, the `mode-line-active` face has to be used, see details at:
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=53636
I've also took the leisure to add a closure to the timer instead of providing arguments to the timer function since the package requires emacs 25.1 anyhow, so support for `lexical-binding` can be assumed.
=> fix(ext-visual-bell): Make it work with emacs 29

extensions/doom-themes-ext-neotree.el
Fixes an old issue where some icons are missing with 
`(setq doom-themes-neotree-file-icons t)`
Fix: https://github.com/doomemacs/themes/issues/180#issuecomment-739877395
Before:
After:
-----
=> fix(ext-neotree): restore missing icons

doom-themes-base.el, themes/doom-gruvbox-light-theme.el, themes/doom-solarized-dark-high-contrast-theme.el
This makes gray readable by way of overriding vterm colors to match the
kitty terminal's gruvbox-light theme
https://github.com/kovidgoyal/kitty-themes/blob/6b06ed8661c62b1fcc63c9de9054d9cc12c319f6/themes/gruvbox-light.conf,
which itself is using colors from the upstream gruvbox palette
https://camo.githubusercontent.com/d080d9c204408ef06b862b76bc795f930b3a9b1be4c5d2de149f1d8eb765b660/687474703a2f2f692e696d6775722e636f6d2f3439714b7959572e706e67.
Unfortunately the variable names associated with this palette are all
over the place in this theme.
Before:
After:
(I have no idea why fish's set_color prints them in this order...)
=> fix(gruvbox-light) make gray readable

extensions/doom-themes-ext-org.el
This pull request fixes the alignment of list items in org-mode when using `mixed-pitch-mode` or similar modes like doom's zen mode. It does so by giving the space characters before the list bullet item and the single space after the bullet item the `org-indent` face.
Org buffer with standard fixed-pitch font:
Org buffer with doom's zen mode activated before the patch:
Org buffer with doom's zen mode activated after the patch:
=> org-mode: align list items in mixed-pitch-mode

themes/doom-nord-aurora-theme.el
I love the Nord theme, but I think it is a bit too monochrome. So I decided to use the [Nord Aurora palette](https://www.nordtheme.com) and create my own. I have been using it for about a year now, and it is very usable, so I think it is time to share it.
=> theme: add doom-nord-aurora

themes/doom-vibrant-theme.el
Hey
Using `doom-vibrant` was difficult on this yaml file, due to the color of `font-lock-variable-name-face`
So i reverted the `base8` color of `variables` to the value from `doom-one`. 
There might be another way to approach this, changing the yaml mode and, but i this was the path of least resistance for me.
If this helps anyone else, this PR exists
Before:
After:
-----
=> tweak(vibrant): use more vivid color for variables

extensions/doom-themes-ext-treemacs.el
pom.xml is not displaying properly in doom treemacs because it is listed explicitly in the treemacs icons code but not listed in the doom treemacs theme as an extension.  
Before:
After
=> fix(ext-treemacs): add icon for pom.xml

doom-themes-base.el
Based on the faces for highlight-symbol, with some reasonable looking choices
for the extra faces symbol-overlay has compared to highlight-symbol.
=> feat(base): add symbol-overlay faces

README.md
Link #faq should be replaced by #customize in the README Table of Contents.
-----
=> docs: fix #customize link in project readme

doom-themes-base.el
https://elpa.gnu.org/packages/disk-usage.html
Before:
Same as after but all elements using the `default` face (all white in this particular case)
After:
(using `doom-tomorrow-night`)
`disk-usage-symlink` mimics what doom-themes does to `dired-symlink` for consistency.
=> feat(base): add disk-usage faces

doom-themes-base.el
By default, `mm-uu-extract` has a `light yellow` foreground and `dark green` background. It's a bit garish.
Before:
Here's an attempt to make this fit in a bit nicer.
**vibrant**
**solarised dark**
**spacegrey**
**one light**
**dracula**
**horizon**
**nord**
**nord light**
**gruvbox**
**gruvbox light**
-----
=> feat(base): add mm-uu-extract face

themes/doom-xcode-theme.el
Emacs 29's `python-ts-mode` is presented in the screenshot, the first window is the original (note `obj.hello`), second window is after adjusting function face, third window is after adjusting rainbow-delimiters.
The window to the right is [VScode - Xcode classic dark](https://marketplace.visualstudio.com/items?itemName=MateoCERQUETELLA.xcode-12-theme) taken for reference (because I don't have access the "real" Xcode).
Fixes #788
-----
=> Xcode function color

doom-themes-base.el
According to Emacs 29.1, they introduce new face for number but this themes doesn't support it yet.
Fixes #771
-----
=> feat(base): add font-lock-number-face

themes/doom-henna-theme.el, themes/doom-homage-black-theme.el, themes/doom-homage-white-theme.el, themes/doom-wilmersdorf-theme.el
I updated the descriptions of Doom-Henna, Doom-Homage-Black Doom, Doom-Homage-White, and Doom Wilmersdorf. I didn't think this was worthy of creating an issue for so I decided to just complete the fix my self.
Fixes #0000
References #0000
Replaces #0000
-----
- [/] I searched the issue tracker and this hasn't been PRed before.
- [/] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [/] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [/] My changes are visual; I've included before and after screenshots.
- [/] Any relevant issues or PRs have been linked to.
=> docs: fix docstring for some themes

doom-themes.el
Replace this with a summary of what you've changed and why, followed by a list of issues it affects, if any.
Fixes #729
-----
=> fix: unescaped quotes in docstring for Emacs 29

themes/doom-acario-dark-theme.el
Avoids
```
Warning: setting attribute ‘:foreground’ of face ‘mode-line’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:background’ of face ‘font-lock-comment-face’: nil value is invalid, use ‘unspecified’ instead.
```
These changes are pretty trivial, but is user facing since it pollutes `*Messages*`.
Related: https://github.com/doomemacs/themes/pull/777/files
However, it misses both cases I've addressed here. So a continuation of: https://github.com/doomemacs/themes/issues/753
I won't promise to get all of them, only the two that bothered me.
-----
=> fix(acario-dark): 'nil value is invalid' warnings

themes/doom-monokai-pro-theme.el
Line numbers with base4 color is hardly visible on screen, changing to base5 as in e.g. monokai-classic.
Here is a screenshoot of the change (left is base4 as un the theme and right is base5 as in this PR):
Fix: #796 
Ref: #796 
Close: #796
-----
=> tweak(monokai-pro): change line-number color base4->base5

doom-themes-base.el
Using 'isearch ensures that the highlight is visible in most themes,
while keeping the same semantics as "searching for a particular string
everywhere".
Close: #766
Ref: #766
Co-Authored-By: @ianyepan 
-----
Changes are in the linked issue
=> fix(base): inherit 'isearch for lsp-ui-peek-highlight

themes/doom-ayu-dark-theme.el, themes/doom-ayu-light-theme.el, themes/doom-ayu-mirage-theme.el
This makes `org-macro` legible across the `ayu` themes.
`ayu-mirage`:
`ayu-dark`:
`ayu-light`:
`ayu-mirage`:
`ayu-dark`:
`ayu-light`:
-----
=> fix(ayu): make org-macro legible

doom-themes-base.el
This adds support for `window-tool-bar`, which is a new package in Emacs 30.
I'm not especially happy that "disabled" just looks borderless, but that's aligned with what the existing tab bar themes do. Ideally I'd like to have a desaturated version of fg/bg but I couldn't figure out how to do that.
-----
- I tried here. Please let me know if you'd like any changes.
- Let me know which theme to show screenshots for. I spot checked ~5 random ones since this affects the theme base.
- I read the text. Not checking this. :) 
- There are no relevant issues.
=> theme: Add support for window-tool-bar, added in Emacs 30

themes/doom-nova-theme.el
Changes some of the faces for the doom-nova theme.
1. The inactive mode line color is lightened to provide a separation between horizontal splits
2. The active mode line color is darkened (preference only)
3. The current vertico selection is darkened so text is readable
Changes:
To:
=> doom-nova visual modifications

themes/doom-molokai-theme.el
Similar to #818. Removes the warnings:
```
Warning: setting attribute ‘:distant-foreground’ of face ‘line-number-current-line’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:distant-foreground’ of face ‘line-number’: nil value is invalid, use ‘unspecified’ instead.
```
Partially fixes #793, Molokai was at least mentioned on this comment https://github.com/doomemacs/themes/issues/793#issuecomment-1946109346
-----
=> fix(molokai): line-number distant-fg - change `nil` -> `'unspecified`

themes/doom-gruvbox-theme.el
This commit fixes a warning Emacs sends regarding the foreground value being set to nil for show-paren faces in the gruvbox theme.
The faces that cause the warning are: 'show-paren-match' and 'show-paren-mismatch'.
Instead of setting it to nil, it is now 'unspecified'.
Common issue it seems like with the new changes to Emacs.
-----
=> Fix: show-paren fg val from 'nil' to 'unspecified'

themes/doom-monokai-classic-theme.el, themes/doom-monokai-machine-theme.el, themes/doom-monokai-octagon-theme.el, themes/doom-monokai-ristretto-theme.el, themes/doom-monokai-spectrum-theme.el
Adds override for face `org-block` to avoid a region within the block begin indistinguishable from the block's background. Uses face `base2` for `org-block{-background,-begin-line]}`.
Theme `doom-theme-monokai-pro` was not included since it doesn't have this problem.
* themes/doom-monokai-classic-theme.el
* themes/doom-monokai-machine-theme.el
* themes/doom-monokai-octagon-theme.el
* themes/doom-monokai-ristretto-theme.el
* themes/doom-monokai-spectrum-theme.el
Fix: #762
-----
Using `doom-monokai-machine` as an example.
=> tweak(monokai): make regions in org blocks visible

themes/doom-gruvbox-theme.el
The original colour didn't belong to the original palette and, tbh, was crimson instead of magenta. I replaced it with the regular original magenta.
Before:
After:
Fixes: #780 
Additionally it kinda makes `rainbow-delimiters` look nicer (before on the right, after on the left):
-----
=> tweak(gruvbox): use magenta from the official palette

doom-themes-base.el
| Before | After |
|-|-|
| ![before](https://github.com/user-attachments/assets/fbd8151b-ec52-40b6-a92b-ce910d6cfe98) | ![after](https://github.com/user-attachments/assets/c7e5099b-cd02-4adc-a8d5-c7ccacec25b6) |
---
The "bright black" color is used in many tools for grayed out foreground text. For example
| Konsole, "One Dark", nodejs | Before (doom-nord, nodejs-repl) | After (doom-nord, nodejs-repl) |
|-|-|-|
| ![konsole nodejs one dark](https://github.com/user-attachments/assets/e201a551-8748-4fbd-b6b7-d6a5b83a1cb1) | ![emacs nodejs-repl nord before](https://github.com/user-attachments/assets/26f04f1b-166f-4dd6-a67d-557eacf3cd26) | ![emacs nodejs-repl nord after](https://github.com/user-attachments/assets/eb53034d-31d4-4d05-9d3b-55ce0a3f4e8c) |
See #833 for other examples.
So this color …
=> fix(base): ansi-color-bright-black should be readable as foreground

themes/doom-winter-is-coming-dark-blue-theme.el, themes/doom-winter-is-coming-light-theme.el, themes/doom-winter-is-coming-theme.el
This theme attempts to replicate the look of the Winter is Coming theme (dark blue variant) for VSCode.
More info: https://marketplace.visualstudio.com/items?itemName=johnpapa.winteriscoming
Replace this with a summary of what you've changed and why, followed by a list of issues it affects, if any.
Fix: #743
Ref: #0000
Close: #743
-----
=> feat(winter-is-coming): add Winter is Coming theme

doom-themes.el
The change makes elisp formatting more consistent with what is currently in `themes/`
-----
=> nit: declare indenting rules for def-doom-themes

themes/doom-homage-black-theme.el, themes/doom-homage-white-theme.el
```emacs-lisp
Debugger entered--Lisp error: (error "Invalid face box" :line-width -1 :color "#383a42" :style 'released-button)
internal-set-lisp-face-attribute(org-date :box (:line-width -1 :color "#383a42" :style 'released-button) #<frame doom-homage-white-theme.el 0x13100ac40>)
set-face-attribute(org-date #<frame doom-homage-white-theme.el 0x13100ac40> :foreground "#383a42" :background "#e7e7e7" :box (:line-width -1 :color "#383a42" :style 'released-button))
apply(set-face-attribute org-date #<frame doom-homage-white-theme.el 0x13100ac40> (:foreground "#383a42" :background "#e7e7e7" :box (:line-width -1 :color "#383a42" :style 'released-button)))
face-spec-set-2(org-date #<frame doom-homage-white-theme.el 0x13100ac40> (:foreground "#383a42" :background "#e7e7e7" :box (:line-width -1 …
```
=> Fix doom-homage themes

doom-themes-base.el
`:italic` is not a font attribute
-----
=> fix(base): replace :italic with :slant

themes/doom-bluloco-light-theme.el
Looking at the screenshots in
https://marketplace.visualstudio.com/items?itemName=uloco.theme-bluloco-light
https://github.com/uloco/theme-bluloco-light
one sees that in the VSCode theme the line numbers are not black but rather grey, like the comments.
Before:
After:
-----
=> fix(bluloco-light): Correct color for line numbers

extensions/doom-themes-ext-treemacs.el
The function `doom-themes-enable-treemacs-variable-pitch-labels` is
executed every time `load-theme` gets called.
Before this fix, each invocation would lead to the treemacs-*-faces
gaining an `:inherit doom-themes-treemacs-variable-pitch-face`
attribute. But inheriting from a face is not an idempotent operation,
i.e., applying it more than once will lead to a different effect than
applying it exactly once. For instance, if the face `variable-pitch` has
the attribute `:height 1.2`, then inheriting from it 4 times will lead
to a height of 1.2^4 ≈ 2 instead of 1.2. Loading 4 themes will therefore
inadvertently double the font size in the treemacs buffer.
With this fix, the inheritance is only applied once.
-----
=> fix(treemacs): inherit from variable-pitch face at most once

themes/doom-zenburn-theme.el
Fix misspelling of foreground resulting in faulty foreground for isearch using zenburn-light theme
=> fix(zenburn-light) :freground -> :foreground

README.md, extensions/doom-themes-ext-neotree.el
I have issues when missing all-the-icons and nerd-icons. It seems that nerd-icons is the new thing, so I updated neotree extension to use it, and it seems to work fine here (both in simple and normal mode)
Related https://github.com/doomemacs/themes/issues/263
-----
=> feat(neotree): replace all-the-icons by nerd-icons

themes/doom-meltbus-theme.el
as reported in https://github.com/doomemacs/themes/issues/854, recent changes to meltbus introduced a syntax error.
This PR fixes the trivial error.
Fix: #854
-----
- [x ] I searched the issue tracker and this hasn't been PRed before.
- [ x] My changes are not on [the do-not-PR list](https://doomemacs.org/donotpr) for this project.
- [x ] My commits conform to [Doom's git conventions](https://doomemacs.org/d/git-conventions).
=> fix(meltbus): fix macroexpansion failure

doom-themes-base.el
This will match the face foreground with that of
[`flycheck-fringe-info`][1] and [`doom-modeline-info`][2].
[1]: https://github.com/doomemacs/themes/blob/2c794a09b023bda09d2f36a7be80684f4e416d88/doom-themes-base.el#L591
[2]: https://github.com/seagle0128/doom-modeline/blob/b782f3c31b966c43fa281fd5fdd07d5c11579e25/doom-modeline-core.el#L780-L781
=> tweak(base): Inherit `flycheck-posframe-info-face` from `success`

README.md
use-package documentation recommends to use ':custom' to set variables
=> docs: follow use-package recommendations

doom-themes-base.el, themes/doom-fairy-floss-theme.el, themes/doom-meltbus-theme.el, themes/doom-nord-aurora-theme.el, themes/doom-nord-theme.el
Ediff colors inherited the same values making it hard to distinguish additions, deletions and fine diffs for most of the themes. `doom-one-light`, for example, solves the issue for itself, but this change tries to fix it for all the themes.
This is the sample before and after for `doom-nord-aurora`
Before:
After:
Following is the video demonstrating the new view for all the themes.
https://github.com/user-attachments/assets/c169fb46-5e2d-48dc-aa56-ed0132b109ef
The PR also makes minor adjustments in themes where the default values don't look proper. These themes are:
- `doom-nord-aurora`
- `doom-nord`
- `doom-meltbus`
- `doom-fairyfloss`
Fix: #847, #792
-----
=> fix ediff highlights for all themes
